name: Find Talent Pool positions

on:
  workflow_dispatch: {}

jobs:
  find:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Run
        env:
          BREEZY_EMAIL: ${{ secrets.BREEZY_EMAIL }}
          BREEZY_PASSWORD: ${{ secrets.BREEZY_PASSWORD }}
        run: node scripts/find_talent_pools.js
